name: Deploy to AWS Amplify

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy to Amplify
        env:
          AWS_REGION: "ap-northeast-2" # Update to Asia (Seoul) region
        run: |
          yarn dlx @aws-amplify/cli amplify publish --yes

      - name: Check Amplify deployment status
        env:
          AWS_REGION: "ap-northeast-2" # Update to Asia (Seoul) region
        run: |
          yarn dlx @aws-amplify/cli amplify status

      - name: Send success Discord notification
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DEPLOYED_URL: ${{ secrets.DEPLOYED_URL }} # 배포된 URL
        uses: Ilshidur/action-discord@master
        with:
          args: |
            # 🎉 배포 완료!
            
            축하합니다! **{{ EVENT_PAYLOAD.repository.full_name }}** 프로젝트가 성공적으로 AWS Amplify에 배포되었습니다!!
            이 URL에서 배포된 웹을 확인하세요: [여기](${{ env.DEPLOYED_URL }})

      - name: Send failure Discord notification
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            # 😢 배포 실패..
            
            **{{ EVENT_PAYLOAD.repository.full_name }}** AWS Amplify 배포에 실패했습니다...
