name: CI Workflow

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment and corepack to use Yarn Berry
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # Enable Corepack to use Yarn Berry
      - name: Enable Corepack
        run: corepack enable

      # Install dependencies using Yarn Berry
      - name: Install dependencies
        run: yarn install

      # Run tests
      - name: Run tests
        run: yarn test --passWithNoTests

      # Build the project
      - name: Build project
        run: yarn build
